---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink : /:year
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Codeando México | #ODD17 Data Showdown"
keywords:    "Codeando México, open data, civic hacking, civic technology, civic tech, open government, opengov"
description: "Codeando México | #ODD17 Data Showdown. El hackatón de datos abiertos en México."
source_link: "https://odd17.codeandomexico.org"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-92890640-1"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#00baff'
  green:     '#9bcf2f' #not in use by ODD
  purple:    '#b108f5' 
  orange:    '#ff8500'
  turquoise: '#fbd831' #this is actually yellow

kramdown:
  auto_ids:  false

